module.exports = {
  apps: [
    {
      name: "script-workspace",
      cwd: "/root/projects/site/script.workspace/apps/web",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3002",
      interpreter: "node",
      env: {
        NODE_ENV: "production",
        BETTER_AUTH_URL: "https://script.yomimovie.art",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "512M",
      error_file: "/root/.pm2/logs/script-workspace-error.log",
      out_file: "/root/.pm2/logs/script-workspace-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "script-admin",
      cwd: "/root/projects/site/script.workspace/apps/admin",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3003",
      interpreter: "node",
      env: {
        NODE_ENV: "production",
        ADMIN_LOGIN: process.env.ADMIN_LOGIN || "",
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD || "",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "256M",
      error_file: "/root/.pm2/logs/script-admin-error.log",
      out_file: "/root/.pm2/logs/script-admin-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "script-collab",
      cwd: "/root/projects/site/script.workspace/apps/collab",
      script: "dist/index.js",
      interpreter: "node",
      env: {
        NODE_ENV: "production",
        COLLAB_PORT: "3004",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "256M",
      error_file: "/root/.pm2/logs/script-collab-error.log",
      out_file: "/root/.pm2/logs/script-collab-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
