export { ScriptEditor, type ScriptEditorProps } from "./components/Editor";
export { EditorToolbar } from "./components/EditorToolbar";
export { useEditorAutosave } from "./hooks/useEditorAutosave";
export { SCREENPLAY_NODES, TAB_CYCLE, ENTER_TRANSITIONS } from "./types/screenplay";
export type { ScreenplayNodeType } from "./types/screenplay";
export type { JSONContent, Editor } from "@tiptap/core";
export { useEditorState } from "@tiptap/react";
export { Fragment } from "@tiptap/pm/model";
export type { SuggestionData } from "./extensions/suggestion-decoration";
export type { AutocompleteState } from "./extensions/autocomplete/autocomplete-extension";
export { autocompletePluginKey } from "./extensions/autocomplete/autocomplete-extension";
export { getScreenplaySchema } from "./schema";
export type { CollaborationConfig } from "./components/Editor";
export { HocuspocusProvider } from "@hocuspocus/provider";
